import httpretty
import json

from four_key_metrics.all_builds import AllBuilds


def httpretty_checks():
    pingdom = {
        "checks": [
            {
                "id": 3966721,
                "created": 1511194948,
                "name": "uk.gov.trade.datahub.api",
                "hostname": "www.datahub.trade.gov.uk",
                "resolution": 1,
                "type": "http",
                "ipv6": "false",
                "verify_certificate": "false",
                "lasterrortime": 1651051310,
                "lasttesttime": 1651572289,
                "lastresponsetime": 320,
                "lastdownstart": 1651051309,
                "lastdownend": 1651051369,
                "status": "up",
            },
            {
                "id": 4946807,
                "created": 1545143412,
                "name": "Data Hub P1",
                "hostname": "www.datahub.trade.gov.uk",
                "resolution": 1,
                "type": "http",
                "ipv6": "false",
                "verify_certificate": "true",
                "lasterrortime": 1649110469,
                "lasttesttime": 1651572269,
                "lastresponsetime": 218,
                "lastdownstart": 1649109749,
                "lastdownend": 1649110529,
                "status": "up",
            },
            {
                "id": 3516241,
                "created": 1504790505,
                "name": "cert check panic 7 day",
                "hostname": "s3-eu-west-1.amazonaws.com",
                "resolution": 1,
                "type": "http",
                "ipv6": "false",
                "verify_certificate": "false",
                "lasterrortime": 1533033907,
                "lasttesttime": 1533033907,
                "lastresponsetime": 0,
                "lastdownstart": 1533033787,
                "status": "paused",
            },
            {
                "id": 5654644,
                "created": 1576234268,
                "name": "Data Hub P2",
                "hostname": "www.datahub.trade.gov.uk",
                "resolution": 1,
                "type": "http",
                "ipv6": "false",
                "verify_certificate": "true",
                "lasterrortime": 1651219794,
                "lasttesttime": 1651572283,
                "lastresponsetime": 645,
                "lastdownstart": 1651219783,
                "lastdownend": 1651219843,
                "status": "up",
            },
            {
                "id": 4709189,
                "created": 1531997684,
                "name": "Domestic UI Staging",
                "hostname": "great.staging.uktrade.digital",
                "resolution": 1,
                "type": "http",
                "ipv6": "false",
                "verify_certificate": "false",
                "lasterrortime": 1651572299,
                "lasttesttime": 1651572299,
                "lastresponsetime": 0,
                "lastdownstart": 1619443963,
                "lastdownend": 1651572299,
                "status": "down",
            },
            {
                "id": 4855100,
                "created": 1541067529,
                "name": "SSO Staging",
                "hostname": "great.staging.uktrade.digital",
                "resolution": 1,
                "type": "http",
                "ipv6": "false",
                "verify_certificate": "true",
                "lasterrortime": 1632785550,
                "lasttesttime": 1651572270,
                "lastresponsetime": 780,
                "lastdownstart": 1632785490,
                "lastdownend": 1632785610,
                "status": "up",
            },
        ],
        "counts": {"total": 6, "limited": 6, "filtered": 1},
    }

    httpretty.register_uri(
        httpretty.GET,
        "https://api.pingdom.com/" "api/3.1/checks/",
        body=json.dumps(pingdom),
    )
    return
