version: 2.1

orbs:
  python: circleci/python@1.2
  slack: circleci/slack@4.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest
      - slack/notify:
          branch_pattern: main
          event: fail
          template: basic_fail_1

workflows:
  primary:
    jobs:
      - test
