version: 2.1

orbs:
  python: circleci/python@1.2

jobs:
  test:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest

workflows:
  primary:
    jobs:
      - test
