version: 2.1

orbs:
  python: circleci/python@1.2
  slack: circleci/slack@4.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: Run tests
          command: poetry run pytest
      - slack/notify:
          branch_pattern: main
          event: fail
          template: basic_fail_1
  update_metrics:
    docker:
      - image: cimg/python:3.11.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          name: clone
          command: git clone git@github.com:uktrade/four-key-metrics.git
      - run:
          name: run script
          command: make scheduled_build
      - run:
          name: commit changes
          command: |
            git checkout Config_Jenkins_For_Autorun
            git add *
            git commit "Triggered deployment [skip ci]"
      - run:
          name: push changes
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "<email>"
            git config user.name "Deployment Bot"
            git push

workflows:
  primary:
    jobs:
      - test
